spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_parts_erp?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # ช่วง dev; พอใช้ Flyway จริงค่อยเปลี่ยนเป็น validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080